version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      open-pull-requests-limit: 25
      schedule:
          interval: "daily"
      groups:
          prod:
              dependency-type: "production"
              patterns:
                  - "*"
          dev:
              dependency-type: "development"
              patterns:
                  - "*"
    - package-ecosystem: "github-actions"
      directory: "/"
      open-pull-requests-limit: 25
      schedule:
          interval: "daily"
      groups:
          prod:
              dependency-type: "production"
              patterns:
                  - "*"
          dev:
              dependency-type: "development"
              patterns:
                  - "*"
